language: python

matrix:
  include:
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "nightly"
  allow_failures:
    - python: "nightly"

before_install:
  - sudo add-apt-repository ppa:texlive-backports/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -y texlive-pictures
  - wget http://mirror.ctan.org/install/macros/latex/contrib/standalone.tds.zip
  - unzip standalone.tds.zip -d ~/texmf
  - sudo texhash
install:
  - pip install -r REQUIREMENTS
  - python setup.py install
script:
  - python setup.py test
  - cd perprof/examples
  - ./make-examples.sh
notifications:
  email:
    - raniere@ime.unicamp.br
    - abel.s.siqueira@gmail.com
  irc: "chat.freenode.net#perprof"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bde89e38372b4ff055cc
    on_success: change
    on_failure: always
