language: python
python:
  - "3.3"
  - "3.4"
install: pip install -r REQUIREMENTS
script: nosetests
notifications:
  email:
    - raniere@ime.unicamp.br
    - abel.s.siqueira@gmail.com
  irc: "chat.freenode.net#perprof"
