# Adapted from https://github.com/codacy/docs/blob/master/.github/workflows/mkdocs.yml#L143
name: Documentation

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  tests:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --extra docs

      - name: Build docs
        run: |
          uv run mkdocs -v build

      - name: Setup doc deploy
        run: |
          git config --global user.name Docs deploy
          git config --global user.email docs@dummy.bot.com

      - name: Deploy docs (dev)
        if: github.ref == 'refs/heads/main'
        run: |
          uv run mike delete dev
          uv run mike deploy --push -t "Documentation for branch main (commit ${GITHUB_SHA::8})" dev

      - name: Deploy docs (tag and latest)
        if: github.ref != 'refs/heads/main'
        run: |
          uv run mike deploy --push --update-aliases -t "Documentation for release $GITHUB_REF_NAME"  $GITHUB_REF_NAME latest
          uv run mike set-default latest
