# Adapted from https://github.com/codacy/docs/blob/master/.github/workflows/mkdocs.yml#L143
name: Documentation

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  tests:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Upgrade pip and install dependencies
        run: |
          pip install --upgrade pip setuptools
          pip install '.[docs]'

      - name: Build docs
        run: |
          mkdocs -v build

      - name: Setup doc deploy
        run: |
          git config --global user.name Docs deploy
          git config --global user.email docs@dummy.bot.com

      - name: Deploy docs (dev)
        if: github.ref == 'refs/heads/main'
        run: |
          mike delete dev
          mike deploy --push --rebase -t "Documentation for branch main (commit ${GITHUB_SHA::8})" dev

      - name: Deploy docs (tag and latest)
        if: github.ref != 'refs/heads/main'
        run: |
          mike deploy --push --update-aliases -t "Documentation for release $GITHUB_REF_NAME"  $GITHUB_REF_NAME latest
          mike set-default latest
