name: Link Checker

on:
  push:
    branches: [main]
    paths:
      - '**.md'
      - '**.markdown'
  pull_request:
    branches: [main]
    paths:
      - '**.md'
      - '**.markdown'

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --exclude-loopback --exclude-private './**/*.md'
          fail: true
