name: Tests

on:
  push:
    branches:
      - main
      - dev-*
  pull_request:
    branches:
      - main
      - dev-*

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Tex stuff
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y texlive-pictures texlive-fonts-recommended texlive-latex-extra

      - name: Upgrade pip and install dependencies
        run: |
          pip install --upgrade pip setuptools
          pip install '.[dev]'

      - name: Run tests
        run: |
          pytest -v

      - name: Run examples
        run: |
          cd perprof/examples
          ./make-examples.sh
