name: Tests

on:
  push:
    branches:
      - main
      - dev-*
  pull_request:
    branches:
      - main
      - dev-*

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Tex stuff
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y texlive-pictures texlive-fonts-recommended texlive-latex-extra

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --group dev

      - name: Run tests
        run: |
          uv run pytest -v

      - name: Run examples
        run: |
          cd perprof/examples
          uv run ./make-examples.sh
